# Generated by Django 4.1.5 on 2023-01-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_form_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='tnc',
            field=models.BooleanField(default=True),
        ),
    ]
